package com.nandaiqbalh.muppi.home_feature.home.presentation

import com.nandaiqbalh.muppi.core.domain.model.Movie
import kotlin.random.Random

data class HomeScreenState(
	val isNowPlayingLoading: Boolean = true,
	val isTopRatedLoading: Boolean = true,
	val isUpcomingMoviesLoading: Boolean = true,
	val isSeriesOnAirLoading: Boolean = true,
	val nowPlaying: List<Movie> = dummyMovies,
	val topRated: List<Movie> = dummyMovies.shuffled(),
	val seriesOnAir: List<Movie> = dummyMovies.shuffled(Random(4)),
	val upcomingMovies: List<Movie> = dummyMovies.shuffled(Random(10))
)

val dummyMovies = listOf(
	Movie(
		adult = false,
		backdropPath = "/gFFqWsjLjRfipKzlzaYPD097FNC.jpg",
		genreIds = listOf(28, 53, 80),
		id = 1126166,
		originalLanguage = "en",
		originalTitle = "Flight Risk",
		overview = "A U.S. Marshal escorts a government witness to trial after he's accused of getting involved with a mob boss...",
		popularity = 25.919,
		posterPath = "/q0bCG4NX32iIEsRFZqRtuvzNCyZ.jpg",
		releaseDate = "2025-01-22",
		title = "Flight Risk",
		video = false,
		voteAverage = 6.12,
		voteCount = 469
	),
	Movie(
		adult = false,
		backdropPath = "/b3mdmjYTEL70j7nuXATUAD9qgu4.jpg",
		genreIds = listOf(16, 14, 12),
		id = 823219,
		originalLanguage = "lv",
		originalTitle = "Straume",
		overview = "A solitary cat, displaced by a great flood, finds refuge on a boat with various species and must navigate the challenges of adapting to a transformed world together.",
		popularity = 13.517,
		posterPath = "/imKSymKBK7o73sajciEmndJoVkR.jpg",
		releaseDate = "2024-08-29",
		title = "Flow",
		video = false,
		voteAverage = 8.3,
		voteCount = 1518
	),
	Movie(
		adult = false,
		backdropPath = "/4HnBkc45h6ABO9i6rbPHTqlKUu8.jpg",
		genreIds = listOf(18, 80),
		id = 1013601,
		originalLanguage = "en",
		originalTitle = "The Alto Knights",
		overview = "Two of New York's most notorious organized crime bosses, Frank Costello and Vito Genovese, vie for control of the city's streets...",
		popularity = 23.418,
		posterPath = "/83XlB51zRozwqpwB4YfCc0AvpTA.jpg",
		releaseDate = "2025-03-14",
		title = "The Alto Knights",
		video = false,
		voteAverage = 0.0,
		voteCount = 0
	),
	Movie(
		adult = false,
		backdropPath = "/gFFqWsjLjRfipKzlzaYPD097FNC.jpg",
		genreIds = listOf(28, 53, 80),
		id = 1126166,
		originalLanguage = "en",
		originalTitle = "Flight Risk",
		overview = "A U.S. Marshal escorts a government witness to trial after he's accused of getting involved with a mob boss, only to discover that the pilot who is transporting them is also a hitman sent to assassinate the informant. After they subdue him, they're forced to fly together after discovering that there are others attempting to eliminate them.",
		popularity = 25.919,
		posterPath = "/q0bCG4NX32iIEsRFZqRtuvzNCyZ.jpg",
		releaseDate = "2025-01-22",
		title = "Flight Risk",
		video = false,
		voteAverage = 6.12,
		voteCount = 469
	),
	Movie(
		adult = false,
		backdropPath = "/87GU2ifjNYtgYtcRH1NNH1P4ODo.jpg",
		genreIds = listOf(18, 35, 10749),
		id = 1064213,
		originalLanguage = "en",
		originalTitle = "Anora",
		overview = "A young sex worker from Brooklyn gets her chance at a Cinderella story when she meets and impulsively marries the son of an oligarch. Once the news reaches Russia, her fairytale is threatened as his parents set out to get the marriage annulled.",
		popularity = 20.921,
		posterPath = "/qh8m8Udz0sCa5gy9VaqfHPh0yPM.jpg",
		releaseDate = "2024-10-14",
		title = "Anora",
		video = false,
		voteAverage = 7.064,
		voteCount = 1700
	),
	Movie(
		adult = false,
		backdropPath = "/9nhjGaFLKtddDPtPaX5EmKqsWdH.jpg",
		genreIds = listOf(10749, 878, 53),
		id = 950396,
		originalLanguage = "en",
		originalTitle = "The Gorge",
		overview = "Two highly trained operatives grow close from a distance after being sent to guard opposite sides of a mysterious gorge. When an evil below emerges, they must work together to survive what lies within.",
		popularity = 27.269,
		posterPath = "/7iMBZzVZtG0oBug4TfqDb9ZxAOa.jpg",
		releaseDate = "2025-02-13",
		title = "The Gorge",
		video = false,
		voteAverage = 7.8,
		voteCount = 1906
	),
	Movie(
		adult = false,
		backdropPath = "/zdNiCWClNFjFvl8KQ5sTlOKmBAB.jpg",
		genreIds = listOf(27),
		id = 1286663,
		originalLanguage = "en",
		originalTitle = "Control Freak",
		overview = "A motivational speaker, plagued by an uncontrollable itch on her head, becomes infected with a parasitic demon from her homeland.",
		popularity = 16.026,
		posterPath = "/kmQb07CrOddVGV0Q73aeU4e8I18.jpg",
		releaseDate = "2025-03-13",
		title = "Control Freak",
		video = false,
		voteAverage = 6.9,
		voteCount = 12
	),
	Movie(
		adult = false,
		backdropPath = "/6J259Zuq09Bt2PLUNeTS5a3DwLZ.jpg",
		genreIds = listOf(28, 53),
		id = 1212855,
		originalLanguage = "en",
		originalTitle = "Fight or Flight",
		overview = "A mercenary takes on the job of tracking down a target on a plane but must protect her when they're surrounded by people trying to kill both of them.",
		popularity = 15.053,
		posterPath = "/x4nWnfgJvL045rcUCSJzfgIIY9i.jpg",
		releaseDate = "2025-03-13",
		title = "Fight or Flight",
		video = false,
		voteAverage = 6.4,
		voteCount = 18
	),
	Movie(
		adult = false,
		backdropPath = "/ywe9S1cOyIhR5yWzK7511NuQ2YX.jpg",
		genreIds = listOf(28, 53, 878),
		id = 822119,
		originalLanguage = "en",
		originalTitle = "Captain America: Brave New World",
		overview = "After meeting with newly elected U.S. President Thaddeus Ross, Sam finds himself in the middle of an international incident. He must discover the reason behind a nefarious global plot before the true mastermind has the entire world seeing red.",
		popularity = 14.42,
		posterPath = "/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg",
		releaseDate = "2025-02-12",
		title = "Captain America: Brave New World",
		video = false,
		voteAverage = 6.174,
		voteCount = 1014
	)
)
